name: search_roof_top_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image:
  connectivity_plus:
  dio: ^5.2.1+1

  flutter:
    sdk: flutter

  flutter_hooks:
  freezed:
  freezed_annotation:
  gap:
  hooks_riverpod: ^2.3.6
  json_annotation:
  package_info_plus: ^4.0.2
  shared_preferences: ^2.1.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  
  pedantic_mono: any
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true