name: search_roof_top_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.1
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1

  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter

  flutter_config: ^2.0.0
  flutter_hooks:
  flutter_native_splash: ^2.3.4
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  fluttericon: ^2.0.0
  freezed:
  freezed_annotation:
  gap: ^3.0.1
  geolocator: ^9.0.2
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.3.1
  hooks_riverpod: ^2.3.6
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation:
  material_floating_search_bar_2: ^0.5.0
  package_info_plus: ^4.0.2
  shared_preferences: ^2.1.2
  tuple: ^2.0.2
  url_launcher: ^6.1.14
  uuid: ^3.0.7


dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  pedantic_mono: any

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  output: lib/utils/gen/
  colors: 
    inputs:
      - assets/colors/colors.xml

flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets/images/restin_large.png'
  color_dark: '#333333'
  image_dark: 'assets/images/restin_large.png'
  fullscreen: true
  android_12:
    icon_background_color: '#FFFFFF'
    image: 'assets/images/restin_large.png'
    icon_background_color_dark: '#333333'
    image_dark: 'assets/images/restin_large.png'

flutter_icons:       
  android: true
  ios: true
  image_path: "assets/images/restin_logo.png"
  adaptive_icon_background: "#ffffff"