name: search_roof_top_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image:
  connectivity_plus:
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1

  firebase_core: ^2.14.0
  flutter:
    sdk: flutter

  flutter_config: ^2.0.0
  flutter_hooks:
  flutter_svg: ^2.0.7
  freezed:
  freezed_annotation:
  gap:
  geolocator: ^9.0.2
  google_maps_flutter: ^2.3.1
  hooks_riverpod: ^2.3.6
  json_annotation:
  package_info_plus: ^4.0.2
  shared_preferences: ^2.1.2


dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  
  pedantic_mono: any

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  output: lib/utils/gen/
  colors: 
    inputs:
      - assets/colors/colors.xml